### ISSUE TITLE
getting this error 

### ISSUE THREAD

**Issue by shivshankar11** [woct0rdho/triton-windows#1]
getting this error 

Loading 1 new model
loaded completely 0.0 11350.048889160156 True
  0%|          | 0/20 [00:00<?, ?it/s]
!!! Exception during processing !!! backend='inductor' raised:
FileNotFoundError: [WinError 2] The system cannot find the file specified

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

Traceback (most recent call last):
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\comfy_extras\nodes_custom_sampler.py", line 633, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\comfy\samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\comfy\samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\comfy\samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\comfy\k_diffusion\sampling.py", line 155, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\comfy\samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\comfy\samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\comfy\samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\comfy\samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\comfy\samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\comfy\model_base.py", line 142, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\eval_frame.py", line 433, in _fn
    return fn(*args, **kwargs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 1116, in __call__
    return self._torchdynamo_orig_callable(
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 948, in __call__
    result = self._inner_convert(
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 472, in __call__
    return _compile(
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_utils_internal.py", line 84, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_strobelight\compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
  File "contextlib.py", line 79, in inner
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 817, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 636, in compile_inner
    out_code = transform_code_object(code, transform)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\bytecode_transformation.py", line 1185, in transform_code_object
    transformations(instructions, code_options)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 178, in _fn
    return fn(*args, **kwargs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 582, in transform
    tracer.run()
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 2451, in run
    super().run()
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 893, in run
    while self.step():
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 497, in wrapper
    return handle_graph_break(self, inst, speculation.reason)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 566, in handle_graph_break
    self.output.compile_subgraph(self, reason=reason)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 1123, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "contextlib.py", line 79, in inner
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 1318, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 1409, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 1390, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\repro\after_dynamo.py", line 129, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\__init__.py", line 1951, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "contextlib.py", line 79, in inner
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 1505, in compile_fx
    return aot_autograd(
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\backends\common.py", line 69, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_functorch\aot_autograd.py", line 954, in aot_module_simplified
    compiled_fn, _ = create_aot_dispatcher_function(
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_functorch\aot_autograd.py", line 687, in create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_functorch\_aot_autograd\jit_compile_runtime_wrappers.py", line 168, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 1410, in fw_compiler_base
    return inner_compile(
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\repro\after_aot.py", line 84, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_inductor\debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "contextlib.py", line 79, in inner
  File "contextlib.py", line 79, in inner
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 527, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "contextlib.py", line 79, in inner
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 831, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_inductor\graph.py", line 1751, in compile_to_fn
    return self.compile_to_module().call
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_inductor\graph.py", line 1680, in compile_to_module
    self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_inductor\graph.py", line 1640, in codegen
    self.scheduler.codegen()
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_dynamo\utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_inductor\scheduler.py", line 2741, in codegen
    self.get_backend(device).codegen_node(node)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_inductor\codegen\cuda_combined_scheduling.py", line 69, in codegen_node
    return self._triton_scheduling.codegen_node(node)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_inductor\codegen\simd.py", line 1148, in codegen_node
    return self.codegen_node_schedule(node_schedule, buf_accesses, numel, rnumel)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_inductor\codegen\simd.py", line 1317, in codegen_node_schedule
    src_code = kernel.codegen_kernel()
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_inductor\codegen\triton.py", line 2159, in codegen_kernel
    **self.inductor_meta_common(),
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\_inductor\codegen\triton.py", line 2047, in inductor_meta_common
    "backend_hash": torch.utils._triton.triton_hash_with_backend(),
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\utils\_triton.py", line 63, in triton_hash_with_backend
    backend = triton_backend()
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\torch\utils\_triton.py", line 49, in triton_backend
    target = driver.active.get_current_target()
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\triton\runtime\driver.py", line 22, in __getattr__
    self._initialize_obj()
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\triton\runtime\driver.py", line 19, in _initialize_obj
    self._obj = self._init_fn()
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\triton\runtime\driver.py", line 8, in _create_driver
    return actives[0]()
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\triton\backends\nvidia\driver.py", line 411, in __init__
    self.utils = CudaUtils()  # TODO: make static
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\triton\backends\nvidia\driver.py", line 55, in __init__
    mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "cuda_utils")
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\triton\backends\nvidia\driver.py", line 32, in compile_module_from_src
    so = _build(name, src_path, tmpdir, library_dir, include_dir, libraries)
  File "S:\Ai\Visual\StabilityMatrix\Data\Packages\ComfyUI 2\venv\lib\site-packages\triton\runtime\build.py", line 69, in _build
    ret = subprocess.check_call(cc_cmd)
  File "subprocess.py", line 364, in check_call
  File "subprocess.py", line 345, in call
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1456, in _execute_child
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
FileNotFoundError: [WinError 2] The system cannot find the file specified

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

**Comment by woct0rdho** [comment]
The latest main branch of triton breaks things with torch v2.4.1. Now I'm trying to move the fixes for windows on top of the released triton v3.0.0 to make things easier

**Comment by shivshankar11** [comment]
tried latest wheel, 
SamplerCustomAdvanced
backend='inductor' raised:
RuntimeError: Failed to find C compiler. Please specify via CC environment variable.

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
import torch._dynamo
torch._dynamo.config.suppress_errors = True

**Comment by FurkanGozukara** [comment]
> The latest main branch of triton breaks things with torch v2.4.1. Now I'm trying to move the fixes for windows onto top of the released triton v3.0.0 to make things easier

i just tested with 2.4.1 here full details

https://github.com/woct0rdho/triton/issues/3#issuecomment-2413463505

**Comment by woct0rdho** [comment]
Hi @shivshankar11 , please install the new wheel `v3.0.0-windows.post1`, run the test script https://github.com/woct0rdho/triton#test-if-it-works , and paste all the results

There is no Windows SDK in your last screenshot. You need to install it

**Comment by Razunter** [comment]
Test fails in my case (Python 3.10 in venv, didn't add "include_libs")
```
Traceback (most recent call last):
  File "d:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\test.py", line 2, in <module>
    import triton
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\__init__.py", line 8, in <module>
    from .runtime import (
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\runtime\__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, autotune, heuristics)
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\runtime\autotuner.py", line 9, in <module>
    from ..testing import do_bench, do_bench_cudagraph
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\testing.py", line 7, in <module>
    from . import language as tl
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\language\__init__.py", line 4, in <module>
    from . import math
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\language\math.py", line 1, in <module>
    from . import core
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\language\core.py", line 10, in <module>
    from ..runtime.jit import jit
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\runtime\jit.py", line 12, in <module>
    from ..runtime.driver import driver
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\runtime\driver.py", line 1, in <module>
    from ..backends import backends
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\backends\__init__.py", line 50, in <module>
    backends = _discover_backends()
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\backends\__init__.py", line 44, in _discover_backends
    driver = _load_module(name, os.path.join(root, name, 'driver.py'))
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\backends\__init__.py", line 12, in _load_module
    spec.loader.exec_module(module)
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\backends\amd\driver.py", line 7, in <module>
    from triton.runtime.build import _build
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\triton\runtime\build.py", line 8, in <module>
    import setuptools
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\setuptools\__init__.py", line 7, in <module>
    import _distutils_hack.override  # noqa: F401
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\_distutils_hack\override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\_distutils_hack\__init__.py", line 77, in do_override
    ensure_local_distutils()
  File "D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\_distutils_hack\__init__.py", line 64, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\Scripts\python310.zip\distutils\core.pyc
```

**Comment by woct0rdho** [comment]
@Razunter It seems the Python installed by StabilityMatrix is an incomplete installation, and it lacks distutils. Please ask the authors of StabilityMatrix to fix that.

**Comment by maxbizz** [comment]
> AssertionError: D:\Soft\StableDiffusion-StabilityMatrix\Data\Packages\ComfyUI\venv\Scripts\python310.zip\distutils\core.pyc
> ```
I have the exact same issue, Have you solved your issue?

**Comment by Razunter** [comment]
@maxbizz sure, I've moved ComfyUI out of StabilityMatrix, deleted and recreated venv, reinstalled all dependencies. Compilation works now, but I didn't notice and boost in speed, and it has no Lora support. I also use GGUF version, so maybe that's related.

**Comment by maxbizz** [comment]
I instaled swarmui just to check if triton really speed up my generation. Sadly i didnt observe any speed improvements. I have a 12gb 3060 card.

**Comment by shivshankar11** [comment]
> I installed swarmui just to check if triton really speed up my generation. Sadly i didnt observe any speed improvements. I have a 12gb 3060 card.

If swarmii is not using torch compile then triton will not do anything. Ask swarmui developers to enable torch compile node. Also lora supported?
