### ISSUE TITLE
ImportError: DLL load failed while importing cuda_utils: The specified module could not be found.

### ISSUE THREAD

**Issue by wtesler** [woct0rdho/triton-windows#21]
I receive this error when trying to run ComfyUI after setting up this project:

`ImportError: DLL load failed while importing cuda_utils: The specified module could not be found.`

I have tried the debugging steps in the README with no luck.

Here is the output when I run dlltracer:

```
LoadLibrary C:\Windows\System32\kernel.appcore.dll
LoadLibrary C:\Windows\System32\apphelp.dll
LoadLibrary W:\PythonProjects\diffuse-design\comfyui\python_embeded\_hashlib.pyd
LoadLibrary W:\PythonProjects\diffuse-design\comfyui\python_embeded\libcrypto-3.dll
LoadLibrary W:\PythonProjects\diffuse-design\comfyui\python_embeded\Lib\site-packages\triton\_C\libtriton.pyd
LoadLibrary W:\PythonProjects\diffuse-design\comfyui\python_embeded\vcruntime140_1.dll
LoadLibrary W:\PythonProjects\diffuse-design\comfyui\python_embeded\msvcp140.dll
LoadLibrary W:\PythonProjects\diffuse-design\comfyui\python_embeded\_bz2.pyd
LoadLibrary W:\PythonProjects\diffuse-design\comfyui\python_embeded\_lzma.pyd
LoadLibrary W:\PythonProjects\diffuse-design\comfyui\python_embeded\_socket.pyd
LoadLibrary W:\PythonProjects\diffuse-design\comfyui\python_embeded\select.pyd
LoadLibrary W:\PythonProjects\diffuse-design\comfyui\python_embeded\_queue.pyd
LoadLibrary W:\PythonProjects\diffuse-design\comfyui\python_embeded\_ssl.pyd
LoadLibrary C:\Windows\System32\crypt32.dll
LoadLibrary W:\PythonProjects\diffuse-design\comfyui\python_embeded\libssl-3.dll
LoadLibrary W:\PythonProjects\diffuse-design\comfyui\python_embeded\_asyncio.pyd
LoadLibrary W:\PythonProjects\diffuse-design\comfyui\python_embeded\_overlapped.pyd
LoadLibrary C:\Windows\System32\mswsock.dll
```

How can I resolve this?

this is the full error:
```
File "W:\PythonProjects\diffuse-design\comfyui\python_embeded\test.py", line 26, in <module>
    b_compiled = add(a, a)
                 ^^^^^^^^^
  File "W:\PythonProjects\diffuse-design\comfyui\python_embeded\test.py", line 21, in add
    add_kernel[grid](x, y, output, n_elements, BLOCK_SIZE=1024)
  File "W:\PythonProjects\diffuse-design\comfyui\python_embeded\Lib\site-packages\triton\runtime\jit.py", line 345, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\PythonProjects\diffuse-design\comfyui\python_embeded\Lib\site-packages\triton\runtime\jit.py", line 607, in run
    device = driver.active.get_current_device()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\PythonProjects\diffuse-design\comfyui\python_embeded\Lib\site-packages\triton\runtime\driver.py", line 23, in __getattr__
    self._initialize_obj()
  File "W:\PythonProjects\diffuse-design\comfyui\python_embeded\Lib\site-packages\triton\runtime\driver.py", line 20, in _initialize_obj
    self._obj = self._init_fn()
                ^^^^^^^^^^^^^^^
  File "W:\PythonProjects\diffuse-design\comfyui\python_embeded\Lib\site-packages\triton\runtime\driver.py", line 9, in _create_driver
    return actives[0]()
           ^^^^^^^^^^^^
  File "W:\PythonProjects\diffuse-design\comfyui\python_embeded\Lib\site-packages\triton\backends\nvidia\driver.py", line 414, in __init__
    self.utils = CudaUtils()  # TODO: make static
                 ^^^^^^^^^^^
  File "W:\PythonProjects\diffuse-design\comfyui\python_embeded\Lib\site-packages\triton\backends\nvidia\driver.py", line 92, in __init__
    mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "cuda_utils")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\PythonProjects\diffuse-design\comfyui\python_embeded\Lib\site-packages\triton\backends\nvidia\driver.py", line 74, in compile_module_from_src
    mod = importlib.util.module_from_spec(spec)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing cuda_utils: The specified module could not be found.
```

**Comment by wtesler** [comment]
After uninstalling and then reinstalling triton, and then clearing the cache, I was able to get it to work.

**Comment by woct0rdho** [comment]
Did dlltracer output some failed messages, like `W:\PythonProjects\diffuse-design\comfyui\python_embeded\...` ? Next time please paste the whole output

**Comment by shirubei** [comment]
same error here.
tried uninstall and reinstall triton but nothing changed.
Please help to show me which cache to clear. thank you.

**Comment by shirubei** [comment]
found the cache folder . Something like 
C:\Users\XXXX\.triton\cache\f586be7c709ab2a9f1ad37d3d552072aa7ffbb2b0baaca2e9eca8d2b05ac1e22

**Comment by Nojahhh** [comment]
I  have reinstalled triton 3.1 (cp311, cuda 12.4) from basically all your posts now.
Deleting all cache-dirs in between.
I still can't get it to work and I'm this close throw this OS out the **window** (pun intended)

I have dug deep in to the triton code as to the last line trying to print directories and `read_text()` from the `cuda_utils` call from `"driver.c"`, just to make sure the configuration is correct and it all matches but it still gives me the same error.

Followed your README.md thoroughly. I'm at a loss right now and it bothers me a great deal.

Traceback:
```
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\nodes.py", line 951, in process
    noise_pred_cond = transformer(
                      ^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\modules\model.py", line 600, in forward
    x = block(x, **kwargs)
        ^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\modules\model.py", line 310, in forward
    y = self.self_attn(
        ^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\modules\model.py", line 152, in forward
    x = attention(
        ^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\modules\attention.py", line 198, in attention
    out = sageattn_func(
          ^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\torch\_dynamo\eval_frame.py", line 632, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WanVideoWrapper\wanvideo\modules\attention.py", line 20, in sageattn_func
    return sageattn(q, k, v, attn_mask=attn_mask, dropout_p=dropout_p, is_causal=is_causal)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\sageattention\core.py", line 105, in sageattn
    q_int8, q_scale, k_int8, k_scale = per_block_int8(q, k, sm_scale=sm_scale, tensor_layout=tensor_layout)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\sageattention\quant_per_block.py", line 63, in per_block_int8
    quant_per_block_int8_kernel[grid](
  File "D:\ComfyUI\python_embeded\Lib\site-packages\triton\runtime\jit.py", line 345, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\triton\runtime\jit.py", line 607, in run
    device = driver.active.get_current_device()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\triton\runtime\driver.py", line 23, in __getattr__
    self._initialize_obj()
  File "D:\ComfyUI\python_embeded\Lib\site-packages\triton\runtime\driver.py", line 20, in _initialize_obj
    self._obj = self._init_fn()
                ^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\triton\runtime\driver.py", line 9, in _create_driver
    return actives[0]()
           ^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\triton\backends\nvidia\driver.py", line 414, in __init__
    self.utils = CudaUtils()  # TODO: make static
                 ^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\triton\backends\nvidia\driver.py", line 92, in __init__
    mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "cuda_utils")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\triton\backends\nvidia\driver.py", line 74, in compile_module_from_src
    mod = importlib.util.module_from_spec(spec)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing cuda_utils: Det går inte att hitta den angivna modulen.
```

dlltracer:
```
LoadLibrary C:\Windows\System32\kernel.appcore.dll
LoadLibrary C:\Windows\System32\apphelp.dll
LoadLibrary D:\ComfyUI\python_embeded\_hashlib.pyd
LoadLibrary D:\ComfyUI\python_embeded\libcrypto-3.dll
LoadLibrary D:\ComfyUI\python_embeded\Lib\site-packages\triton\_C\libtriton.pyd
LoadLibrary D:\ComfyUI\python_embeded\vcruntime140_1.dll
LoadLibrary D:\ComfyUI\python_embeded\msvcp140.dll
LoadLibrary D:\ComfyUI\python_embeded\_bz2.pyd
LoadLibrary D:\ComfyUI\python_embeded\_lzma.pyd
LoadLibrary D:\ComfyUI\python_embeded\_socket.pyd
LoadLibrary D:\ComfyUI\python_embeded\select.pyd
LoadLibrary D:\ComfyUI\python_embeded\_queue.pyd
LoadLibrary D:\ComfyUI\python_embeded\_ssl.pyd
LoadLibrary C:\Windows\System32\crypt32.dll
LoadLibrary D:\ComfyUI\python_embeded\libssl-3.dll
LoadLibrary D:\ComfyUI\python_embeded\_asyncio.pyd
LoadLibrary D:\ComfyUI\python_embeded\_overlapped.pyd
LoadLibrary C:\Windows\System32\mswsock.dll
```
