### ISSUE TITLE
FileNotFound error

### ISSUE THREAD

**Issue by jpgallegoar** [woct0rdho/triton-windows#22]
I keep getting this error when trying the test

(hun) PS E:\AI\triton> python test.py
Traceback (most recent call last):
  File "E:\AI\triton\test.py", line 26, in <module>
    b_compiled = add(a, a)
                 ^^^^^^^^^
  File "E:\AI\triton\test.py", line 21, in add
    add_kernel[grid](x, y, output, n_elements, BLOCK_SIZE=1024)
  File "C:\Users\thega\miniconda3\envs\hun\Lib\site-packages\triton\runtime\jit.py", line 345, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thega\miniconda3\envs\hun\Lib\site-packages\triton\runtime\jit.py", line 607, in run
    device = driver.active.get_current_device()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thega\miniconda3\envs\hun\Lib\site-packages\triton\runtime\driver.py", line 23, in __getattr__
    self._initialize_obj()
  File "C:\Users\thega\miniconda3\envs\hun\Lib\site-packages\triton\runtime\driver.py", line 20, in _initialize_obj
    self._obj = self._init_fn()
                ^^^^^^^^^^^^^^^
  File "C:\Users\thega\miniconda3\envs\hun\Lib\site-packages\triton\runtime\driver.py", line 9, in _create_driver
    return actives[0]()
           ^^^^^^^^^^^^
  File "C:\Users\thega\miniconda3\envs\hun\Lib\site-packages\triton\backends\nvidia\driver.py", line 414, in __init__
    self.utils = CudaUtils()  # TODO: make static
                 ^^^^^^^^^^^
  File "C:\Users\thega\miniconda3\envs\hun\Lib\site-packages\triton\backends\nvidia\driver.py", line 92, in __init__
    mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "cuda_utils")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thega\miniconda3\envs\hun\Lib\site-packages\triton\backends\nvidia\driver.py", line 69, in compile_module_from_src
    so = _build(name, src_path, tmpdir, library_dirs(), include_dir, libraries)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thega\miniconda3\envs\hun\Lib\site-packages\triton\runtime\build.py", line 71, in _build
    ret = subprocess.check_call(cc_cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thega\miniconda3\envs\hun\Lib\subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thega\miniconda3\envs\hun\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thega\miniconda3\envs\hun\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\thega\miniconda3\envs\hun\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

It says FileNotFound but doesn't specify which one

**Comment by woct0rdho** [comment]
The subprocess in `triton\runtime\build.py`, line 71 calls `cl`, so most likely you did not properly install MSVC on your computer. What happens if you open a new PowerShell and type `cl`?

**Comment by jpgallegoar** [comment]
Thank you for your answer! I managed to fix it in the end but forgot about this post. I did hace cl working, but I think the main problem was having a different version of CUDA than the app required, broken PATHs... Reinstalling VS fully also helped.

**Comment by FurkanGozukara** [comment]
@woct0rdho i have MSVC installed but when i type cl i get error

![image](https://github.com/user-attachments/assets/01d365ea-f10c-48dd-872b-240e67449408)

**Comment by woct0rdho** [comment]
@FurkanGozukara Then you need to add the path containing `cl.exe` to the Windows `PATH`

Sometimes people uses `x64 Native Tools Command Prompt` or `vcvarsall.bat` to set the path, but from my experience that may mess up with the environment

**Comment by FurkanGozukara** [comment]
@woct0rdho thanks do you have any preferred version?

![image](https://github.com/user-attachments/assets/5fb67215-e3a6-4c42-9439-79d6ff6dd000)

**Comment by woct0rdho** [comment]
Usually you just need the highest version and you can uninstall all others

**Comment by FurkanGozukara** [comment]
@woct0rdho ty so much

i add path like this right? and it looks accurate to you? 

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\cl.exe
