### ISSUE TITLE
DLL load failed while importing libtriton

### ISSUE THREAD

**Issue by czcz1024** [woct0rdho/triton-windows#26]
when i use a comfyui node,it's failed with error:

Traceback (most recent call last):
File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\utils\import_utils.py", line 853, in get_module
return importlib.import_module("." + module_name, self.name)
File "D:\ai\ComfyUI\python\lib\importlib_init.py", line 126, in import_module
return bootstrap.gcd_import(name[level:], package, level)
File "", line 1050, in gcd_import
File "", line 1027, in find_and_load
File "", line 1006, in find_and_load_unlocked
File "", line 688, in load_unlocked
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\models\modeling_utils.py", line 35, in
from ..quantizers import DiffusersAutoQuantizer, DiffusersQuantizer
File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\quantizers_init.py", line 15, in
from .auto import DiffusersAutoQuantizer
File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\quantizers\auto.py", line 21, in
from .bitsandbytes import BnB4BitDiffusersQuantizer, BnB8BitDiffusersQuantizer
File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\quantizers\bitsandbytes_init.py", line 2, in
from .utils import dequantize_and_replace, dequantize_bnb_weight, replace_with_bnb_linear
File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\quantizers\bitsandbytes\utils.py", line 32, in
import bitsandbytes as bnb
File "D:\ai\ComfyUI\python\lib\site-packages\bitsandbytes_init.py", line 15, in
from .nn import modules
File "D:\ai\ComfyUI\python\lib\site-packages\bitsandbytes\nn_init.py", line 21, in
from .triton_based_modules import (
File "D:\ai\ComfyUI\python\lib\site-packages\bitsandbytes\nn\triton_based_modules.py", line 6, in
from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise
File "D:\ai\ComfyUI\python\lib\site-packages\bitsandbytes\triton\dequantize_rowwise.py", line 12, in
import triton
File "D:\ai\ComfyUI\python\lib\site-packages\triton_init.py", line 20, in
from .runtime import (
File "D:\ai\ComfyUI\python\lib\site-packages\triton\runtime_init.py", line 1, in
from .autotuner import (Autotuner, Config, Heuristics, autotune, heuristics)
File "D:\ai\ComfyUI\python\lib\site-packages\triton\runtime\autotuner.py", line 9, in
from ..testing import do_bench, do_bench_cudagraph
File "D:\ai\ComfyUI\python\lib\site-packages\triton\testing.py", line 7, in
from . import language as tl
File "D:\ai\ComfyUI\python\lib\site-packages\triton\language_init.py", line 4, in
from . import math
File "D:\ai\ComfyUI\python\lib\site-packages\triton\language\math.py", line 1, in
from . import core
File "D:\ai\ComfyUI\python\lib\site-packages\triton\language\core.py", line 10, in
from ..runtime.jit import jit
File "D:\ai\ComfyUI\python\lib\site-packages\triton\runtime\jit.py", line 12, in
from ..runtime.driver import driver
File "D:\ai\ComfyUI\python\lib\site-packages\triton\runtime\driver.py", line 1, in
from ..backends import backends
File "D:\ai\ComfyUI\python\lib\site-packages\triton\backends_init_.py", line 50, in
backends = discover_backends()
File "D:\ai\ComfyUI\python\lib\site-packages\triton\backends_init.py", line 43, in _discover_backends
compiler = load_module(name, os.path.join(root, name, 'compiler.py'))
File "D:\ai\ComfyUI\python\lib\site-packages\triton\backends_init.py", line 12, in _load_module
spec.loader.exec_module(module)
File "D:\ai\ComfyUI\python\lib\site-packages\triton\backends\amd\compiler.py", line 2, in
from triton._C.libtriton import ir, passes, llvm, amd
ImportError: DLL load failed while importing libtriton: 动态链接库(DLL)初始化例程失败。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "D:\ai\ComfyUI\nodes.py", line 2035, in load_custom_node
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "D:\ai\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper_init.py", line 1, in
from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
File "D:\ai\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 12, in
from .hyvideo.modules.posemb_layers import get_nd_rotary_pos_embed
File "D:\ai\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\modules_init_.py", line 1, in
from .models import HYVideoDiffusionTransformer, HUNYUAN_VIDEO_CONFIG
File "D:\ai\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\modules\models.py", line 8, in
from diffusers.models import ModelMixin
File "", line 1075, in _handle_fromlist
File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\utils\import_utils.py", line 843, in getattr
module = self._get_module(self._class_to_module[name])
File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\utils\import_utils.py", line 855, in _get_module
raise RuntimeError(
RuntimeError: Failed to import diffusers.models.modeling_utils because of the following error (look up to see its traceback):
DLL load failed while importing libtriton: 动态链接库(DLL)初始化例程失败。

Cannot import D:\ai\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper module for custom nodes: Failed to import diffusers.models.modeling_utils because of the following error (look up to see its traceback):
DLL load failed while importing libtriton: 动态链接库(DLL)初始化例程失败。

**Comment by osagem** [comment]
the same:
`(base) PS K:\ai\comfylAI\ComfyUI_windows_portable> .\python_embeded\python.exe
Python 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import dlltracer
>>> with dlltracer.Trace(out=sys.stdout):
... import diffusers
  File "<stdin>", line 2
    import diffusers
    ^
IndentationError: expected an indented block after 'with' statement on line 1
>>> import triton
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "K:\ai\comfylAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\__init__.py", line 20, in <module>
    from .runtime import (
  File "K:\ai\comfylAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\runtime\__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, autotune, heuristics)
  File "K:\ai\comfylAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\runtime\autotuner.py", line 9, in <module>
    from ..testing import do_bench, do_bench_cudagraph
  File "K:\ai\comfylAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\testing.py", line 7, in <module>
    from . import language as tl
  File "K:\ai\comfylAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\language\__init__.py", line 4, in <module>
    from . import math
  File "K:\ai\comfylAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\language\math.py", line 1, in <module>
    from . import core
  File "K:\ai\comfylAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\language\core.py", line 10, in <module>
    from ..runtime.jit import jit
  File "K:\ai\comfylAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\runtime\jit.py", line 12, in <module>
    from ..runtime.driver import driver
  File "K:\ai\comfylAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\runtime\driver.py", line 1, in <module>
    from ..backends import backends
  File "K:\ai\comfylAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\backends\__init__.py", line 50, in <module>
    backends = _discover_backends()
               ^^^^^^^^^^^^^^^^^^^^
  File "K:\ai\comfylAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\backends\__init__.py", line 43, in _discover_backends
    compiler = _load_module(name, os.path.join(root, name, 'compiler.py'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\ai\comfylAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\backends\__init__.py", line 12, in _load_module
    spec.loader.exec_module(module)
  File "K:\ai\comfylAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\backends\amd\compiler.py", line 2, in <module>
    from triton._C.libtriton import ir, passes, llvm, amd
ImportError: DLL load failed while importing libtriton: 动态链接库(DLL)初始化例程失败。
>>>
`

**Comment by osagem** [comment]
finally found the reason
file msvcp140.dll is not copied properly. (but everything was normal yesterday, I don't know which packages were updated by comfyui today... LOL)

refer here
https://github.com/woct0rdho/triton-windows?tab=readme-ov-file#test-if-it-works

`
(base) PS K:\ai\comfylAI\ComfyUI_windows_portable> .\python_embeded\python.exe '.\triton test.py'
main.c
  正在创建库 main.lib 和对象 main.exp
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function 'add_kernel' for 'sm_89'
ptxas info    : Function properties for add_kernel
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 26 registers, 380 bytes cmem[0]
main.c
  正在创建库 main.lib 和对象 main.exp
tensor([0., 0., 0.], device='cuda:0')
If you see tensor([0., 0., 0.], device='cuda:0'), then it works
(base) PS K:\ai\comfylAI\ComfyUI_windows_portable>
`

**Comment by LorisTecnology** [comment]
> finally found my problem reason file msvcp140.dll is not copied properly, other two vc dll files were already in place before. (but everything was normal yesterday, I don't know which packages were updated by comfyui today... LOL)
> 
> refer here https://github.com/woct0rdho/triton-windows?tab=readme-ov-file#test-if-it-works
> 
> (base) PS K:\ai\comfylAI\ComfyUI_windows_portable> .\python_embeded\python.exe '.\triton test.py' main.c 正在创建库 main.lib 和对象 main.exp ptxas info : 0 bytes gmem ptxas info : Compiling entry function 'add_kernel' for 'sm_89' ptxas info : Function properties for add_kernel 0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads ptxas info : Used 26 registers, 380 bytes cmem[0] main.c 正在创建库 main.lib 和对象 main.exp tensor([0., 0., 0.], device='cuda:0') If you see tensor([0., 0., 0.], device='cuda:0'), then it works (base) PS K:\ai\comfylAI\ComfyUI_windows_portable>

so your install works with Python 3.11.6?
