### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by cliffordkleinsr** [woct0rdho/triton-windows#8]
When I run test.py I get an error:
```sh
(mt3) PS C:\Users\cliffordkleinsr\Documents> python test.py
Traceback (most recent call last):
  File "C:\Users\cliffordkleinsr\Documents\test.py", line 26, in <module>
    b_compiled = add(a, a)
                 ^^^^^^^^^
  File "C:\Users\cliffordkleinsr\Documents\test.py", line 21, in add
    add_kernel[grid](x, y, output, n_elements, BLOCK_SIZE=1024)
  File "C:\Users\cliffordkleinsr\anaconda3\envs\mt3\Lib\site-packages\triton\runtime\jit.py", line 345, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cliffordkleinsr\anaconda3\envs\mt3\Lib\site-packages\triton\runtime\jit.py", line 662, in run
    kernel = self.compile(
             ^^^^^^^^^^^^^
  File "C:\Users\cliffordkleinsr\anaconda3\envs\mt3\Lib\site-packages\triton\compiler\compiler.py", line 244, in compile
    key = f"{triton_key()}-{src.hash()}-{backend.hash()}-{options.hash()}-{str(sorted(env_vars.items()))}"
                                         ^^^^^^^^^^^^^^
  File "C:\Users\cliffordkleinsr\anaconda3\envs\mt3\Lib\site-packages\triton\backends\nvidia\compiler.py", line 336, in hash
    version = get_ptxas_version()
              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cliffordkleinsr\anaconda3\envs\mt3\Lib\site-packages\triton\backends\nvidia\compiler.py", line 38, in get_ptxas_version
    version = subprocess.check_output([_path_to_binary("ptxas")[0], "--version"]).decode("utf-8")
                                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cliffordkleinsr\anaconda3\envs\mt3\Lib\site-packages\triton\backends\nvidia\compiler.py", line 23, in _path_to_binary
    os.path.join(os.environ.get("CUDA_PATH"), "bin", binary),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 108, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
I have everything installed:
cuda:
```sh
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:36:15_Pacific_Daylight_Time_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
(mt3) PS C:\Users\cliffordkleinsr\Documents>
```
cl:
```sh
(mt3) PS C:\Users\cliffordkleinsr\Documents> cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.39.33521 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
```
torch:
```python
>>> import torch
>>> torch.version.cuda
'12.1'
```
Environment variables:
![image](https://github.com/user-attachments/assets/8eb870eb-37f7-4a55-854b-a129dc8c07f3)

python, Triton, and pytorch versions:
```sh
triton  3.1.0 
python  3.11.10 
pytorch  2.5.0
```

**Comment by cliffordkleinsr** [comment]
![image](https://github.com/user-attachments/assets/0015ed46-8494-4ff1-a6e7-06a149cfe82b)
This might be the reason, for anyone having problems. just change the CUDA_PATH or modify the script to use your CUDA_PATH. Many thanks to @woct0rdho for this windows port ❤️
